# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://rahuketu86.github.io/tvec/"

git_url = "https://github.com/rahuketu86/tvec/tree/master/"

def custom_doc_links(name): return None
